import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { openDatabase } from '../../db/database.js';
import { ArrAdapter } from './adapter.js';
import { ArrTransport } from './common/transport.js';
import { ArrStateStore } from './state.js';

type Fixture = Record<string, unknown>;
const fixture = (provider: 'sonarr' | 'radarr') => JSON.parse(readFileSync(`tests/fixtures/${provider}/${provider === 'sonarr' ? '4.0' : '5.0'}-synthetic/data.json`, 'utf8')) as Fixture;
function adapter(provider: 'sonarr' | 'radarr', source: Fixture, calls: { url: string; init?: RequestInit }[] = []) { const fetcher = vi.fn((input: string | URL | Request, init?: RequestInit) => { const url = input instanceof Request ? input.url : input.toString(); calls.push({ url, ...(init ? { init } : {}) }); const path = new URL(url).pathname; const key = path.endsWith('/system/status') ? 'status' : path.endsWith('/health') ? 'health' : path.endsWith('/queue') ? 'queue' : path.endsWith('/wanted/missing') ? 'missing' : path.endsWith('/calendar') ? 'calendar' : path.endsWith('/history') ? 'history' : 'catalog'; return Promise.resolve(new Response(JSON.stringify(source[key]), { status: 200 })); }); return new ArrAdapter(provider, new ArrTransport(`http://${provider}.test/prefix`, `${provider}-secret`, fetcher)); }

describe('Arr integrations', () => {
  it.each(['sonarr', 'radarr'] as const)('%s uses fixed GET routes, path prefixes and X-Api-Key authentication', async (provider) => { const calls: { url: string; init?: RequestInit }[] = []; const subject = adapter(provider, fixture(provider), calls); await subject.connection(); await subject.queue(); expect(calls.every((call) => call.init?.method === 'GET' && call.init.redirect === 'error')).toBe(true); expect(calls[0]?.url).toContain(`http://${provider}.test/prefix/api/v3/system/status`); expect(calls[0]?.init?.headers).toMatchObject({ 'X-Api-Key': `${provider}-secret` }); });
  it('normalizes Sonarr queue, safe warning, monitored/missing, episode date and imports', async () => { const subject = adapter('sonarr', fixture('sonarr')); expect((await subject.health()).data.warnings).toEqual(['Service reports a warning']); const queue = (await subject.queue()).data; expect(queue.entries[0]).toMatchObject({ source: 'sonarr', id: '7', progressRatio: .75, stage: 'downloading' }); expect(queue.entries[1]?.warnings).toEqual(['Download reported a warning']); expect(JSON.stringify(queue)).not.toContain('LABDECK_SECRET'); const catalog = (await subject.catalog()).data; expect(catalog).toMatchObject({ monitored: 1, missing: 3 }); expect(catalog.upcoming[0]).toMatchObject({ title: 'Example Station', releaseKind: 'episode-air', date: '2026-09-24T20:00:00.000Z' }); expect((await subject.history()).data.imports[0]).toMatchObject({ id: '101', title: 'Example Station' }); });
  it('keeps Radarr IDs source-scoped and maps timezone-aware digital release without inventing progress', async () => { const subject = adapter('radarr', fixture('radarr')); const queue = (await subject.queue()).data.entries[0]; expect(queue).toMatchObject({ source: 'radarr', id: '7', progressRatio: null, stage: 'unknown' }); const catalog = (await subject.catalog()).data; expect(catalog).toMatchObject({ monitored: 2, missing: 1 }); expect(catalog.upcoming[0]).toMatchObject({ releaseKind: 'digital', date: '2026-09-25T04:00:00.000Z' }); });
  it('marks capped queue projections as truncated while retaining authoritative totals', async () => { const source = fixture('sonarr'); source.queue = { page: 1, pageSize: 100, totalRecords: 75, records: Array.from({ length: 75 }, (_, id) => ({ id, title: `Episode ${id}`, size: 100, sizeleft: 50, status: 'downloading' })) }; const queue = (await adapter('sonarr', source).queue()).data; expect(queue.entries).toHaveLength(50); expect(queue).toMatchObject({ total: 75, truncated: true }); });
  it('paginates locally constructed pages and stops after a partial last page', async () => { const calls: string[] = []; const fetcher = vi.fn((input: string | URL | Request) => { const url = new URL(input instanceof Request ? input.url : input.toString()); calls.push(url.toString()); const page = Number(url.searchParams.get('page')); const records = page === 1 ? Array.from({ length: 100 }, (_, id) => ({ id })) : [{ id: 100 }]; return Promise.resolve(new Response(JSON.stringify({ page, pageSize: 100, totalRecords: 101, records }))); }); const result = await new ArrTransport('http://sonarr.test', 'secret', fetcher).getPaged('/api/v3/queue', {}); expect(result).toMatchObject({ totalRecords: 101, complete: true }); expect(result.records).toHaveLength(101); expect(calls).toHaveLength(2); expect(calls[1]).toContain('page=2'); });
  it('baselines import history and commits cursor plus non-duplicate events transactionally', async () => { const database = openDatabase(':memory:'); const state = new ArrStateStore(database, 'sonarr'); const subject = adapter('sonarr', fixture('sonarr')); const first = await subject.history(); state.success('history', first, 1); expect(database.prepare('SELECT count(*) AS count FROM events').get()).toEqual({ count: 0 }); const second = structuredClone(first); second.data.imports.unshift({ id: '102', title: 'New Import', importedAt: '2026-09-23T10:00:00.000Z' }); state.success('history', second, 2); state.success('history', second, 3); expect(database.prepare("SELECT count(*) AS count FROM events WHERE kind='downloads.imported'").get()).toEqual({ count: 1 }); const cursor = database.prepare("SELECT cursor_json FROM poll_state WHERE instance_id='sonarr' AND group_id='history'").get() as { cursor_json: string }; expect(cursor.cursor_json).toContain('102'); database.close(); });
  it('rolls back the history cursor when event persistence fails', async () => { const database = openDatabase(':memory:'); const state = new ArrStateStore(database, 'sonarr'); const first = await adapter('sonarr', fixture('sonarr')).history(); state.success('history', first, 1); database.exec("CREATE TRIGGER reject_import BEFORE INSERT ON events WHEN NEW.kind='downloads.imported' BEGIN SELECT RAISE(ABORT, 'synthetic failure'); END"); const second = structuredClone(first); second.data.imports.unshift({ id: '102', title: 'Rollback Import', importedAt: null }); state.success('history', second, 2); const row = database.prepare("SELECT cursor_json FROM poll_state WHERE instance_id='sonarr' AND group_id='history'").get() as { cursor_json: string }; expect(row.cursor_json).not.toContain('102'); expect(state.historyAvailable).toBe(false); database.close(); });
});
