import type Database from 'better-sqlite3';
import { persistEvent, retainEvents } from '../../core/events.js';
import { SafeTransportError } from '../../core/read-only-transport.js';
import type { ArrKind, ArrObservation, CatalogData, HistoryData, QueueEntry } from './adapter.js';

export type ArrGroup = 'connection' | 'health' | 'queue' | 'catalog' | 'history';
type Observation = ArrObservation<{ warnings: string[] }> | ArrObservation<{ entries: QueueEntry[]; total: number; truncated: boolean }> | ArrObservation<CatalogData> | ArrObservation<HistoryData> | { version: string };
export class ArrStateStore {
  historyAvailable = true;
  constructor(private readonly database: Database.Database, readonly kind: ArrKind) {}
  success(group: ArrGroup, observation: Observation, now = Date.now()): void { try { this.database.transaction(() => {
    const previousIds = group === 'history' ? this.historyIds() : undefined;
    if ('observedAt' in observation) this.database.prepare(`INSERT INTO capability_state(instance_id,capability,schema_version,observed_at,succeeded_at,normalized_json) VALUES (?,?,'1',?,?,?) ON CONFLICT(instance_id,capability) DO UPDATE SET observed_at=excluded.observed_at,succeeded_at=excluded.succeeded_at,normalized_json=excluded.normalized_json`).run(this.kind, `downloads.${group}`, Date.parse(observation.observedAt), now, JSON.stringify(observation));
    let cursor: string | null = null;
    if (group === 'history') { const ids = (observation as ArrObservation<HistoryData>).data.imports.map((item) => item.id); cursor = JSON.stringify([...new Set([...(previousIds ?? []), ...ids])].slice(-1000)); }
    this.database.prepare(`INSERT INTO poll_state(instance_id,group_id,last_success_at,attempted_at,safe_error_code,cursor_json) VALUES (?,?,?, ?,NULL,?) ON CONFLICT(instance_id,group_id) DO UPDATE SET last_success_at=excluded.last_success_at,attempted_at=excluded.attempted_at,safe_error_code=NULL,cursor_json=COALESCE(excluded.cursor_json,poll_state.cursor_json)`).run(this.kind, group, now, now, cursor);
    if (group === 'connection') this.connectionSuccess(now);
    if (group === 'history' && previousIds) for (const item of (observation as ArrObservation<HistoryData>).data.imports) if (!previousIds.has(item.id)) persistEvent(this.database, { instanceId: this.kind, entityId: `import:${item.id}`, kind: 'downloads.imported', severity: 'info', ...(item.importedAt ? { occurredAt: Date.parse(item.importedAt) } : {}), observedAt: now, origin: 'upstream', dedupeKey: `${this.kind}:import:${item.id}`, payload: { source: this.kind, title: item.title } });
    retainEvents(this.database, now);
  })(); } catch { this.historyAvailable = false; } }
  failure(group: ArrGroup, error: unknown, now = Date.now()): void { const code = error instanceof SafeTransportError ? error.code : error instanceof Error && error.message === 'invalid-response' ? 'invalid-response' : 'internal'; try { this.database.transaction(() => {
    this.database.prepare(`INSERT INTO poll_state(instance_id,group_id,attempted_at,safe_error_code) VALUES (?,?,?,?) ON CONFLICT(instance_id,group_id) DO UPDATE SET attempted_at=excluded.attempted_at,safe_error_code=excluded.safe_error_code`).run(this.kind, group, now, code);
    if (group === 'connection') { const prior = this.database.prepare('SELECT consecutive_failures,succeeded_at FROM integration_state WHERE instance_id=?').get(this.kind) as { consecutive_failures: number; succeeded_at: number | null } | undefined; const failures = (prior?.consecutive_failures ?? 0) + 1; this.database.prepare(`INSERT INTO integration_state(instance_id,config_revision,connection,attempted_at,safe_error_code,consecutive_failures) VALUES (?,'1',?,?,?,?) ON CONFLICT(instance_id) DO UPDATE SET connection=excluded.connection,attempted_at=excluded.attempted_at,safe_error_code=excluded.safe_error_code,consecutive_failures=excluded.consecutive_failures`).run(this.kind, code === 'auth' ? 'auth-error' : 'unreachable', now, code, failures); if (failures === 2 && prior?.succeeded_at) persistEvent(this.database, { instanceId: this.kind, kind: 'integration.outage', severity: 'warning', observedAt: now, origin: 'observed', dedupeKey: `${this.kind}:outage:${now}`, payload: { integration: this.kind, errorCode: code } }); }
  })(); } catch { this.historyAvailable = false; } }
  private connectionSuccess(now: number) { const prior = this.database.prepare('SELECT consecutive_failures,succeeded_at FROM integration_state WHERE instance_id=?').get(this.kind) as { consecutive_failures: number; succeeded_at: number | null } | undefined; this.database.prepare(`INSERT INTO integration_state(instance_id,config_revision,connection,attempted_at,succeeded_at,safe_error_code,consecutive_failures) VALUES (?,'1','reachable',?,?,NULL,0) ON CONFLICT(instance_id) DO UPDATE SET connection='reachable',attempted_at=excluded.attempted_at,succeeded_at=excluded.succeeded_at,safe_error_code=NULL,consecutive_failures=0`).run(this.kind, now, now); if (prior && prior.consecutive_failures >= 2 && prior.succeeded_at) persistEvent(this.database, { instanceId: this.kind, kind: 'integration.recovered', severity: 'info', observedAt: now, origin: 'observed', dedupeKey: `${this.kind}:recovered:${now}`, payload: { integration: this.kind } }); }
  private historyIds(): Set<string> | undefined { const row = this.database.prepare('SELECT cursor_json FROM poll_state WHERE instance_id=? AND group_id=?').get(this.kind, 'history') as { cursor_json: string | null } | undefined; if (!row?.cursor_json) return undefined; try { return new Set(JSON.parse(row.cursor_json) as string[]); } catch { return undefined; } }
}
