import { OrderedWidgets, useSelectedStorage } from '../../components/OrderedWidgets.js';
import { ProblemList } from '../problems/ProblemPage.js';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Cpu, HardDrive, MemoryStick, Network, ServerCog } from 'lucide-react';
import { SessionCard } from '../media/MediaPage.js';
import { Link } from 'react-router-dom';
import { getOverview } from '../../app/api.js';
import { bytes, duration, relativeTime } from '../../components/format.js';
import { Status, type StatusTone } from '../../components/Status.js';

export function OverviewPage() {
  const overview = useQuery({ queryKey: ['overview'], queryFn: getOverview, refetchInterval: 5_000, refetchIntervalInBackground: false });
  const selected = useSelectedStorage(overview.data?.configured ? overview.data.storage : null);
  const selectedStorage = selected.storage;
  return <main id="main-content" tabIndex={-1}>
    <header className="page-header"><div><p className="eyebrow">OVERVIEW</p><h1>Your homelab</h1></div><p className="page-context">Local monitoring</p></header>
    {overview.isPending ? <div className="panel loading-panel" aria-label="Loading overview"><span className="skeleton" /></div> : null}
    {overview.isError ? <div className="notice" role="alert"><Status tone="critical">Unavailable</Status><h2>LabDeck could not load its cached state</h2><p>Check the application status and try again.</p></div> : null}
    {overview.data && !overview.data.configured ? <section className="empty-state" aria-labelledby="empty-title"><div className="empty-icon" aria-hidden="true"><ServerCog size={24} /></div><Status tone="unknown">Monitoring incomplete</Status><h2 id="empty-title">{overview.data.title}</h2><p>{overview.data.message}</p><Link className="text-link" to="/settings">Review setup <ArrowRight aria-hidden="true" size={15} /></Link></section> : null}
    {overview.data?.configured ? <>
      <section className="health-strip panel"><div><Status tone={tone(overview.data.overall)}>{overview.data.title}</Status><p>{overview.data.message}</p></div><span className="refresh-age">Observed {relativeTime(overview.data.observedAt)}</span></section>
      <ProblemList />
      <OrderedWidgets className="overview-widgets">
      <section data-widget="system" className="metric-grid" aria-label="Host health">
        <Metric icon={<Cpu size={17} />} label="CPU" value={overview.data.host?.cpu.utilizationPercent === null || !overview.data.host ? 'Collecting' : `${overview.data.host.cpu.utilizationPercent.toFixed(1)}%`} detail={overview.data.host ? `Load ${overview.data.host.load.one.toFixed(2)}` : 'No observation'} />
        <Metric icon={<MemoryStick size={17} />} label="Memory" value={overview.data.host ? `${Math.round((overview.data.host.memory.usedBytes / overview.data.host.memory.totalBytes) * 100)}%` : '—'} detail={overview.data.host ? `${bytes(overview.data.host.memory.availableBytes)} available` : 'No observation'} />
        <Metric icon={<HardDrive size={17} />} label="Storage" value={selectedStorage ? `${Math.round(selectedStorage.usedRatio * 100)}%` : '—'} detail={selectedStorage ? `${bytes(selectedStorage.availableBytes)} available` : 'No selected volume'} />
        <Metric icon={<ServerCog size={17} />} label="Uptime" value={overview.data.host ? duration(overview.data.host.uptimeSeconds) : '—'} detail={overview.data.host?.hostname ?? 'Waiting for host'} />
        <Metric icon={<Network size={17} />} label="Network" value={rate(overview.data.network?.receiveBytesPerSecond)} detail={overview.data.network ? `↑ ${rate(overview.data.network.transmitBytesPerSecond)} · ${overview.data.network.name}` : 'No selected interface'} />
        <Metric icon={<HardDrive size={17} />} label="Disk I/O" value={rate(overview.data.diskIo?.readBytesPerSecond)} detail={overview.data.diskIo ? `Write ${rate(overview.data.diskIo.writeBytesPerSecond)} · ${overview.data.diskIo.name}` : 'No selected device'} />
      </section>
      {selectedStorage ? <section data-widget="storage" className="panel storage-summary"><div className="section-heading"><div><h2>{selectedStorage.id}</h2><p>{selectedStorage.path} · {selectedStorage.fsType}</p></div><strong>{bytes(selectedStorage.availableBytes)} available</strong></div><p className="fine-print">{selected.failed ? 'Refresh failed · ' : ''}{selected.freshness ?? overview.data.freshness} · observed {relativeTime(selected.observedAt ?? overview.data.observedAt)}</p><div className="capacity-track"><span style={{ width: `${Math.min(100, selectedStorage.usedRatio * 100)}%` }} /></div><div className="capacity-labels"><span>{bytes(selectedStorage.usedBytes)} used</span><span>{bytes(selectedStorage.totalBytes)} total</span></div></section> : null}
      {overview.data.media ? <section data-widget="watching" className="panel media-section"><div className="section-heading"><div><h2>Currently watching</h2><p>{overview.data.media.errorCode ? 'Refresh failed · showing last-good sessions.' : `${overview.data.media.sessions.filter((session) => !session.paused).length} playing · ${overview.data.media.sessions.filter((session) => session.paused).length} paused`}</p></div><div className="summary-action"><Status tone={overview.data.media.connection === 'reachable' ? overview.data.media.freshness === 'fresh' ? 'healthy' : 'warning' : overview.data.media.connection === 'unknown' ? 'unknown' : 'warning'}>{overview.data.media.connection === 'auth-error' ? 'Credentials rejected' : overview.data.media.connection === 'unreachable' ? 'Unreachable' : overview.data.media.freshness === 'stale' ? 'Stale' : overview.data.media.connection === 'reachable' ? 'Reachable' : 'Checking'}</Status><Link className="text-link" to="/media">Media <ArrowRight size={14} /></Link></div></div>{overview.data.media.sessions.length ? <div className="session-list">{overview.data.media.sessions.slice(0, 4).map((session) => <SessionCard key={`${session.id}:${session.mediaId}`} session={session} />)}</div> : <p className="muted">{overview.data.media.freshness === 'never' ? 'Waiting for Jellyfin playback data.' : 'Nobody is watching right now.'}</p>}</section> : null}
      {overview.data.downloads.length ? <section data-widget="downloads" className="service-grid">{overview.data.downloads.map((service) => <article className="panel" key={service.id}><div className="section-heading"><div><h2>{service.name}</h2><p>{service.queueTotal} queue {service.queueTotal === 1 ? 'entry' : 'entries'} · {service.catalog?.missing ?? '—'} missing</p></div><Status tone={service.connection === 'reachable' ? service.healthWarnings.length ? 'warning' : 'healthy' : service.connection === 'unknown' ? 'unknown' : 'warning'}>{service.connection === 'auth-error' ? 'Credentials rejected' : service.connection}</Status></div></article>)}</section> : null}
      {overview.data.indexers ? <section data-widget="downloads" className="panel"><div className="section-heading"><div><h2>Prowlarr</h2><p>{overview.data.indexers.failingTotal === null ? 'Waiting for indexer evidence' : `${overview.data.indexers.failingTotal} failing · ${overview.data.indexers.disabledTotal} disabled`} · observed {relativeTime(overview.data.indexers.observedAt)}</p></div><div className="summary-action"><Status tone={overview.data.indexers.connection !== 'reachable' || overview.data.indexers.freshness !== 'fresh' ? 'warning' : (overview.data.indexers.failingTotal ?? 0) > 0 ? 'warning' : 'healthy'}>{overview.data.indexers.connection === 'auth-error' ? 'Credentials rejected' : overview.data.indexers.freshness === 'stale' ? 'Stale' : overview.data.indexers.connection === 'reachable' ? 'Reachable' : overview.data.indexers.connection}</Status><Link className="text-link" to="/downloads">Indexers <ArrowRight size={14} /></Link></div></div></section> : null}
      {overview.data.containers ? <section data-widget="docker" className="panel media-section"><div className="section-heading"><div><h2>Containers</h2><p>{overview.data.containers.total === null ? 'Inventory incomplete' : `${overview.data.containers.running ?? '—'} of ${overview.data.containers.total} running`} · {(overview.data.containers.unhealthy ?? 0)} unhealthy · observed {relativeTime(overview.data.containers.observedAt)}</p></div><div className="summary-action"><Status tone={overview.data.containers.freshness !== 'fresh' ? 'unknown' : (overview.data.containers.unhealthy ?? 0) > 0 || (overview.data.containers.expectedStopped ?? 0) > 0 ? 'warning' : 'healthy'}>{overview.data.containers.freshness === 'fresh' ? 'Current' : overview.data.containers.freshness === 'stale' ? 'Stale' : 'Waiting'}</Status><Link className="text-link" to="/containers">Containers <ArrowRight size={14} /></Link></div></div></section> : null}
      {overview.data.disks ? <section data-widget="storage" className="panel media-section"><div className="section-heading"><div><h2>Physical disks</h2><p>{overview.data.disks.failed} failed · {overview.data.disks.warning} warning · {overview.data.disks.unavailable} unavailable · observed {relativeTime(overview.data.disks.observedAt)}</p></div><div className="summary-action"><Status tone={overview.data.disks.freshness !== 'fresh' ? 'unknown' : overview.data.disks.failed ? 'critical' : overview.data.disks.warning ? 'warning' : 'healthy'}>{overview.data.disks.freshness === 'fresh' ? 'Current evidence' : 'Stale evidence'}</Status><Link className="text-link" to="/storage">Disk details <ArrowRight size={14} /></Link></div></div></section> : null}
      {overview.data.tailscale ? <section data-widget="network" className="panel media-section"><div className="section-heading"><div><h2>Tailscale</h2><p>{overview.data.tailscale.total === null ? 'Local peer count unknown' : `${overview.data.tailscale.online ?? 0} of ${overview.data.tailscale.total} locally known peers reported online`} · observed {relativeTime(overview.data.tailscale.observedAt)}</p></div><div className="summary-action"><Status tone={overview.data.tailscale.freshness === 'fresh' && overview.data.tailscale.backendState === 'Running' ? 'healthy' : 'unknown'}>{overview.data.tailscale.backendState ?? 'Waiting'}</Status><Link className="text-link" to="/network">Network <ArrowRight size={14} /></Link></div></div></section> : null}
      </OrderedWidgets>
      <section className="panel recent-events"><div className="section-heading"><div><h2>Recent activity</h2><p>Transitions observed by LabDeck.</p></div><Link className="text-link" to="/events">All events <ArrowRight size={14} /></Link></div>{overview.data.events.length ? <ul className="event-list">{overview.data.events.map((event) => <li key={event.id}><span className={`event-dot event-dot--${event.severity}`} /><span>{eventTitle(event.kind, event.payload)}</span><time>{relativeTime(event.observedAt)}</time></li>)}</ul> : <p className="muted">No noteworthy transitions yet.</p>}</section>
    </> : null}
  </main>;
}

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="metric-card"><div className="metric-label">{icon}{label}</div><strong>{value}</strong><span>{detail}</span></article>; }
function tone(status: 'healthy' | 'warning' | 'critical' | 'monitoring-incomplete'): StatusTone { return status === 'monitoring-incomplete' ? 'unknown' : status; }
function rate(value: number | null | undefined): string { return value === null ? 'Collecting' : value === undefined ? '—' : `${bytes(value)}/s`; }
function eventTitle(kind: string, payload: Record<string, string | number | boolean | null>): string { const source = payload.integration === 'jellyfin' ? 'Jellyfin' : payload.integration === 'sonarr' ? 'Sonarr' : payload.integration === 'radarr' ? 'Radarr' : payload.integration === 'prowlarr' ? 'Prowlarr' : 'Host collector'; return ({ 'integration.outage': `${source} connection lost`, 'integration.recovered': `${source} connection recovered`, 'indexer.failure-observed': 'Indexer failure observed', 'indexer.failure-cleared': 'Indexer failure cleared', 'container.restart-observed': 'Container restart observed', 'container.recreated-observed': 'Container recreation observed', 'disk.smart-failed': 'SMART failure evidence observed', 'disk.smart-warning': 'SMART warning observed', 'disk.error-increase': 'Disk error counter increased', 'disk.capacity-changed': 'Physical disk capacity changed', 'disk.temperature-high': 'Disk temperature high', 'disk.temperature-recovered': 'Disk temperature recovered', 'disk.replaced-observed': 'Physical disk replacement observed', 'media.playback-observed': 'Playback observed', 'downloads.imported': `${payload.source === 'radarr' ? 'Radarr' : 'Sonarr'} import`, 'storage.threshold': 'Storage crossed a capacity threshold', 'storage.recovered': 'Storage returned below its warning threshold' } as Record<string, string>)[kind] ?? 'Observed status changed'; }
