import { useQuery } from '@tanstack/react-query';
import { getEvents } from '../../app/api.js';
import { relativeTime } from '../../components/format.js';

function eventTitle(kind: string, payload: Record<string, string | number | boolean | null>) { const source = payload.integration === 'jellyfin' ? 'Jellyfin' : payload.integration === 'sonarr' ? 'Sonarr' : payload.integration === 'radarr' ? 'Radarr' : 'Host collector'; return ({ 'integration.outage': `${source} connection lost`, 'integration.recovered': `${source} connection recovered`, 'media.playback-observed': 'Playback observed', 'downloads.imported': `${payload.source === 'radarr' ? 'Radarr' : 'Sonarr'} import`, 'storage.threshold': 'Storage crossed a capacity threshold', 'storage.recovered': 'Storage returned below its warning threshold', 'container.restart-observed': 'Container restart observed', 'container.recreated-observed': 'Container recreation observed', 'disk.smart-failed': 'SMART failure evidence observed', 'disk.smart-warning': 'SMART warning observed', 'disk.error-increase': 'Disk error counter increased', 'disk.capacity-changed': 'Physical disk capacity changed', 'disk.temperature-high': 'Disk temperature high', 'disk.temperature-recovered': 'Disk temperature recovered', 'disk.replaced-observed': 'Physical disk replacement observed' } as Record<string, string>)[kind] ?? 'Observed status changed'; }
export function EventsPage() {
  const query = useQuery({ queryKey: ['events'], queryFn: getEvents, refetchInterval: 10_000 });
  return <main id="main-content" tabIndex={-1}><header className="page-header"><div><p className="eyebrow">ACTIVITY</p><h1>Events</h1></div></header>
    <section className="panel"><div className="section-heading"><div><h2>Observed transitions</h2><p>Deduplicated state changes from configured integrations.</p></div></div>{query.isError ? <p role="alert" className="form-error">Cached events are unavailable.</p> : query.data?.events.length ? <ul className="event-list event-list--large">{query.data.events.map((event) => <li key={event.id}><span className={`event-dot event-dot--${event.severity}`} aria-hidden="true" /><span><strong>{eventTitle(event.kind, event.payload)}</strong><small>{event.entityId ?? (event.payload.integration === 'jellyfin' ? 'Jellyfin' : 'Host')}</small></span><time dateTime={event.observedAt} title={new Date(event.observedAt).toLocaleString()}>{relativeTime(event.observedAt)}</time></li>)}</ul> : <p className="muted">{query.isPending ? 'Loading events…' : 'No noteworthy transitions yet.'}</p>}</section>
  </main>;
}
