import { SmartTests, SmartSchedule } from './SmartTests.js';
import { usePreferences } from '../../app/preferences.js';
import { StorageForecastPanel } from './StorageForecastPanel.js';
import { useQuery } from '@tanstack/react-query';
import { getStorage } from '../../app/api.js';
import { bytes, relativeTime } from '../../components/format.js';
import { Sparkline } from '../../components/Sparkline.js';
import { Status } from '../../components/Status.js';
import type { HistoryRange } from '@labdeck/contracts';

export function StoragePage() {
  const [preferences, updatePreferences] = usePreferences();
  const range = preferences.historyRange, selectedId = preferences.selectedVolume;
  const setRange = (historyRange: HistoryRange) => updatePreferences({ historyRange });
  const setSelectedId = (selectedVolume: string) => updatePreferences({ selectedVolume });
  const query = useQuery({ queryKey: ['storage', range], queryFn: () => getStorage(range), refetchInterval: 15_000 });
  const selected = query.data?.filesystems.find((item) => item.id === selectedId) ?? query.data?.filesystems[0];
  return <main id="main-content" tabIndex={-1}><header className="page-header"><div><p className="eyebrow">CAPACITY</p><h1>Storage</h1></div></header>
    {query.data ? <><div className="detail-toolbar"><Status tone={query.data.freshness === 'fresh' ? 'healthy' : 'unknown'}>{query.data.freshness === 'fresh' ? 'Current' : 'Stale'}</Status><span>Observed {relativeTime(query.data.observedAt)}</span><div className="segmented" role="group" aria-label="History range">{(['1h', '24h', '7d', '30d', '400d'] as const).map((item) => <button key={item} type="button" aria-pressed={range === item} className={range === item ? 'active' : ''} onClick={() => setRange(item)}>{item}</button>)}</div></div>
      {selected ? <><label className="volume-selector" htmlFor="volume-select">Selected filesystem <select id="volume-select" value={selected.id} onChange={(event) => setSelectedId(event.target.value)}>{query.data.filesystems.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.path}</option>)}</select></label><section className="volume-list"><article className="panel volume-card"><div className="section-heading"><div><h2>{selected.id}</h2><p>{selected.path} · {selected.source}</p></div><strong>{Math.round(selected.usedRatio * 100)}% used</strong></div><div className="capacity-segments" role="img" aria-label={`${bytes(selected.usedBytes)} used, ${bytes(selected.reservedBytes)} reserved, ${bytes(selected.availableBytes)} available`}><span className="capacity-used" style={{ width: `${selected.totalBytes ? selected.usedBytes / selected.totalBytes * 100 : 0}%` }} /><span className="capacity-reserved" style={{ width: `${selected.totalBytes ? selected.reservedBytes / selected.totalBytes * 100 : 0}%` }} /><span className="capacity-available" style={{ flex: 1 }} /></div><div className="capacity-labels"><span>{bytes(selected.usedBytes)} used</span><span>{bytes(selected.reservedBytes)} reserved</span><span>{bytes(selected.availableBytes)} available</span><span>{bytes(selected.totalBytes)} total</span></div><Sparkline label={`${selected.id} used capacity history`} values={(query.data.history[selected.id] ?? []).map((point) => point.value)} /><StorageForecastPanel forecast={query.data.forecasts?.[selected.id]} /><p className="fine-print">Filesystem capacity is separate from physical-disk capacity. Available is allocatable by an unprivileged process.</p></article></section></> : null}
      {!query.data.filesystems.length ? <section className="notice"><Status tone="unknown">Monitoring incomplete</Status><h2>No selected volumes</h2><p>Configure at least one explicit filesystem in the host collector.</p></section> : null}</> : <section className="notice" role={query.isError ? 'alert' : undefined}><h2>{query.isError ? 'Cached storage state is unavailable' : 'Loading storage…'}</h2></section>}
    {query.data ? <section className="disk-section"><div className="section-heading"><div><h2>Physical disks</h2><p>SMART evidence does not guarantee future disk safety. Disk capacity is not added to filesystem capacity.</p></div><Status tone={query.data.smart.freshness === 'fresh' ? 'healthy' : 'unknown'}>{!query.data.smart.configured ? 'Not configured' : query.data.smart.freshness === 'fresh' ? 'Observed' : 'Stale'}</Status></div>{query.data.smart.errorCode ? <p className="form-error">SMART snapshot read failed ({query.data.smart.errorCode}); showing last-good evidence.</p> : null}{query.data.smart.disks.length ? <div className="disk-list">{query.data.smart.disks.map((disk) => <article className="panel" key={disk.id}><div className="section-heading"><div><h3>{disk.label}</h3><p>{disk.model || 'Model unknown'} · {disk.protocol} · {disk.serialSuffix ? `serial …${disk.serialSuffix}` : 'identity unknown'}</p></div><Status tone={disk.state !== 'ok' ? 'unknown' : disk.health === 'failed' ? 'critical' : disk.health === 'warning' || disk.temperatureWarning ? 'warning' : disk.health === 'passed' ? 'healthy' : 'unknown'}>{disk.state !== 'ok' ? disk.state.replace('-', ' ') : disk.health === 'passed' ? 'SMART passed' : disk.health}</Status></div><p className="muted">Status observed {relativeTime(disk.observedAt)} · health evidence {relativeTime(disk.evidenceAt)}</p><div className="disk-facts"><span>Temperature <strong>{disk.temperatureCelsius === null ? 'Unknown' : `${disk.temperatureCelsius}°C${disk.temperatureWarning ? ' · high' : ''}`}</strong></span><span>Capacity <strong>{disk.capacityBytes === null ? 'Unknown' : bytes(disk.capacityBytes)}</strong></span><span>Power-on <strong>{disk.powerOnHours === null ? 'Unknown' : `${disk.powerOnHours.toLocaleString()} h`}</strong></span></div>{disk.ata ? <p className="fine-print">ATA sectors: {disk.ata.reallocated || 'unknown'} reallocated · {disk.ata.pending || 'unknown'} pending · {disk.ata.uncorrectable || 'unknown'} uncorrectable.</p> : null}{disk.nvme ? <p className="fine-print">NVMe: {disk.nvme.availableSparePercent ?? 'unknown'}% spare · {disk.nvme.percentageUsed ?? 'unknown'}% used · {disk.nvme.mediaErrors || 'unknown'} media errors · {disk.nvme.errorLogEntries || 'unknown'} error log entries.</p> : null}{disk.scsi ? <p className="fine-print">SCSI: {disk.scsi.grownDefects || 'unknown'} grown defects · {disk.scsi.readUncorrected || 'unknown'} uncorrected reads.</p> : null}<SmartTests disk={disk} controlAvailable={query.data.smart.testControlAvailable ?? false} canStart={query.data.smart.freshness === 'fresh' && !query.data.smart.errorCode && disk.state === 'ok' && disk.selfTest?.state !== 'running'} /></article>)}</div> : <p className="muted">{query.data.smart.configured ? 'Waiting for disk evidence.' : 'Configure the separate SMART helper to observe physical disks.'}</p>}</section> : null}
    <SmartSchedule />
  </main>;
}
